spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/servexa_appointment
    
eureka:
  instance:
    hostname: appointment-service

# Vehicle service configuration for Docker
vehicle:
  service:
    url: http://vehicle-service:8084