spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/notification_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    
services:
  auth-service:
    url: ${AUTH_SERVICE_URL:http://auth-service:8081}
    
redis:
  host: ${REDIS_HOST:redis}
  port: ${REDIS_PORT:6379}