services:
  postgres:
    image: postgres:15-alpine
    container_name: servexa-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: servexa_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: servexa-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: